export const dashboardHtml = `<!doctype html>
<html lang="pt-AO"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TRIA · AppyPay Connector</title><style>
:root{color-scheme:dark;--bg:#080b12;--panel:#101621;--line:#202b3b;--text:#f5f7fb;--muted:#8d9aab;--blue:#1687ff;--yellow:#ffc928;--green:#24c875;--red:#ff6262}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% -20%,#17345a 0,transparent 35%),var(--bg);font:14px Inter,system-ui,sans-serif;color:var(--text)}main{max-width:1240px;margin:auto;padding:36px 24px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:28px}.brand{display:flex;gap:13px;align-items:center}.logo{width:42px;height:42px;border-radius:12px;background:linear-gradient(135deg,var(--blue),#55b0ff);display:grid;place-items:center;font-weight:900;font-size:18px}.eyebrow{color:var(--yellow);font-size:11px;font-weight:800;letter-spacing:.14em}.brand h1{font-size:20px;margin:4px 0 0}.mode{border:1px solid #285d43;background:#102d21;color:#65e3a1;padding:8px 12px;border-radius:999px;font-weight:700}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.card,.tablebox,.integration{background:linear-gradient(145deg,rgba(18,25,37,.96),rgba(12,17,26,.96));border:1px solid var(--line);border-radius:16px}.card{padding:19px}.card span{color:var(--muted);font-size:12px}.card strong{display:block;font-size:26px;margin-top:10px}.integration{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:16px 19px;margin-bottom:20px}.integration-info{display:flex;align-items:center;gap:12px}.integration-dot{width:10px;height:10px;border-radius:50%;background:var(--muted)}.integration.connected .integration-dot{background:var(--green);box-shadow:0 0 0 5px rgba(36,200,117,.12)}.integration strong{display:block}.integration small{display:block;color:var(--muted);margin-top:4px}.integration-meta{color:var(--muted);text-align:right;font-size:12px}.toolbar{display:flex;gap:10px;padding:16px;border-bottom:1px solid var(--line)}select,button{background:#0b111b;border:1px solid var(--line);color:var(--text);padding:10px 12px;border-radius:10px}button{cursor:pointer;background:var(--blue);border:0;font-weight:700;margin-left:auto}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:900px}th,td{text-align:left;padding:14px 16px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}.status{font-size:11px;font-weight:800;padding:5px 8px;border-radius:999px;background:#2a2413;color:var(--yellow)}.status.PAID{background:#123423;color:#62dfa0}.status.FAILED,.status.CANCELLED,.status.EXPIRED{background:#351a1d;color:#ff8989}.method{font-weight:700}.empty{text-align:center;color:var(--muted);padding:48px}footer{color:var(--muted);font-size:12px;margin-top:18px;text-align:right}@media(max-width:760px){.cards{grid-template-columns:1fr 1fr}.top,.integration{align-items:flex-start;gap:14px}.integration{flex-direction:column}.integration-meta{text-align:left}.toolbar{flex-wrap:wrap}}
</style></head><body><main><div class="top"><div class="brand"><div class="logo">T</div><div><div class="eyebrow">TRIA COMPANY</div><h1>AppyPay · Shopify Connector</h1></div></div><div class="mode">● AppyPay simulado</div></div>
<section class="integration" id="shopify-status"><div class="integration-info"><span class="integration-dot"></span><div><strong id="shopify-title">Verificando Shopify…</strong><small id="shopify-shop">Aguardando dados da instalação</small></div></div><div class="integration-meta" id="shopify-meta"></div></section>
<section class="cards"><div class="card"><span>Transações</span><strong id="total">—</strong></div><div class="card"><span>Pendentes</span><strong id="pending">—</strong></div><div class="card"><span>Valor total</span><strong id="amount">—</strong></div><div class="card"><span>Lojas Shopify instaladas</span><strong id="merchants">—</strong></div></section>
<section class="tablebox"><div class="toolbar"><select id="status"><option value="">Todos os status</option><option>PENDING</option><option>PAID</option><option>FAILED</option><option>EXPIRED</option><option>CANCELLED</option></select><select id="method"><option value="">Todos os métodos</option><option value="REFERENCE">Referência</option><option value="MULTICAIXA_EXPRESS">MULTICAIXA Express</option></select><button id="refresh">Atualizar</button></div><div class="tablewrap"><table><thead><tr><th>Data</th><th>Comerciante</th><th>Método</th><th>Valor</th><th>Status</th><th>Referência / sessão</th><th>ID AppyPay</th></tr></thead><tbody id="rows"></tbody></table></div></section><footer>Atualização automática a cada 15 segundos · Ambiente UAT</footer></main>
<script src="/dashboard.js" defer></script></body></html>`;

export const dashboardScript = `let data=[],installations=[];
const kz=new Intl.NumberFormat('pt-AO',{style:'currency',currency:'AOA'});
const dt=new Intl.DateTimeFormat('pt-AO',{dateStyle:'short',timeStyle:'short'});
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function paint(){const s=document.querySelector('#status').value,m=document.querySelector('#method').value,rows=data.filter(x=>(!s||x.status===s)&&(!m||x.method===m));document.querySelector('#total').textContent=data.length;document.querySelector('#pending').textContent=data.filter(x=>x.status==='PENDING').length;document.querySelector('#amount').textContent=kz.format(data.reduce((a,x)=>a+x.amountMinor,0)/100);document.querySelector('#merchants').textContent=installations.filter(x=>x.active).length;document.querySelector('#rows').innerHTML=rows.length?rows.map(x=>'<tr><td>'+dt.format(new Date(x.createdAt))+'</td><td>'+esc(x.merchant)+'</td><td class="method">'+(x.method==='REFERENCE'?'Referência':'MULTICAIXA Express')+'</td><td>'+kz.format(x.amountMinor/100)+'</td><td><span class="status '+esc(x.status)+'">'+esc(x.status)+'</span></td><td>'+esc(x.reference||x.shopifySessionId)+'</td><td>'+esc(x.providerPaymentId)+'</td></tr>').join(''):'<tr><td colspan="7" class="empty">Nenhuma transação AppyPay encontrada</td></tr>'}
function paintShopify(){const active=installations.find(x=>x.active),box=document.querySelector('#shopify-status');if(!active){box.classList.remove('connected');document.querySelector('#shopify-title').textContent='Shopify não conectado';document.querySelector('#shopify-shop').textContent='Nenhuma instalação OAuth ativa';document.querySelector('#shopify-meta').textContent='';return}box.classList.add('connected');document.querySelector('#shopify-title').textContent='Shopify conectado';document.querySelector('#shopify-shop').textContent=active.shopDomain;document.querySelector('#shopify-meta').textContent='Escopo: '+(active.shopifyScopes||'não informado')+' · Instalado em '+(active.installedAt?dt.format(new Date(active.installedAt)):'data não informada')}
async function load(){try{const responses=await Promise.all([fetch('/v1/payments'),fetch('/v1/shopify/installations')]);if(responses.some(r=>!r.ok))throw new Error('Falha ao carregar o dashboard');[data,installations]=await Promise.all(responses.map(r=>r.json()));paint();paintShopify()}catch(error){document.querySelector('#rows').innerHTML='<tr><td colspan="7" class="empty">Não foi possível carregar os dados.</td></tr>';console.error(error)}}
document.querySelector('#status').onchange=paint;document.querySelector('#method').onchange=paint;document.querySelector('#refresh').onclick=load;load();setInterval(load,15000);`;
